name: Inference

on:
  workflow_dispatch:
    inputs:
      forecast_days:
        description: 'Number of days to forecast'
        required: true
        default: '7'
        type: choice
        options:
        - '1'
        - '3'
        - '7'
        - '14'
        - '30'

permissions:
  contents: write  # 👈 REQUIRED to allow pushing changes

jobs:
  inference:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # 👈 needed for committing changes

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run inference
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
          FORECAST_DAYS: ${{ github.event.inputs.forecast_days }}
        run: python run_inference.py --forecast-days $FORECAST_DAYS
